### PR TITLE
EOS cryptography proposal 1/2 - Milestone 2

### PR DESCRIPTION
**Pull request by lukapercic**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/8

### CODE REVIEW

**Comment by smlu** [comment]
@larryk85 thank you for spotting this issue I've updated the code and should be fixed now.

**Review by larryk85 — APPROVED** [review]

**Review by DenisCarriere — APPROVED** [review]
## Milestone delivery

- [x] Includes proper documentation & testing guide
- [x] Deployed on Jungle/Kylin (account=`helloeosiock`)
- [x] Released under MIT open source license

Milestone appears to be completed

**Review by spoonincode — APPROVED** [review]
Looking great. btw consider modifying the opening paragraph of the README which doesn't mention PSS (obviously the rest of the readme makes it clear, it's just the leading paragraph I noticed didn't mention it)
https://github.com/ZeroPass/antelope.ck/blob/master/README.md?plain=1#L7

**Comment by smlu** [comment]
Thanks for spotting that, it must have slipped in the revision process. I'll update the readme file.

**Review by arhag — APPROVED** [review]
LGTM.

By the way, the links to the two header files under the [Algorithm testing](https://github.com/ZeroPass/antelope.ck#algorithm-testing) section of the [README](https://github.com/ZeroPass/antelope.ck/blob/49a4bb1e5a415ee9ce2226533248fc3a91364e5a/README.md) are broken and need to be updated to reflect the correct relative path.

**Review by wanderingbort — APPROVED** [review]
Apologies I should have approved earlier when I initially reviewed.

**Pull request merged**
