### PR TITLE
Create alphaday-1.md

### PR DESCRIPTION
**Pull request by Mikael337**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/XXX < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by nsjames** [comment]
Absolutely fantastic work. Reviewed during the process as well with Zack 👍

**Review by nsjames — APPROVED** [review]

**Review by lparisc — APPROVED** [review]
- Tested portal functionality at https://app.alphaday.com/b/eos/
- All sections are cohesive and respond/render correctly.
- Suggestion for EOS documentation section:
  * Render Smart Contract, Web App, and Node Operator journeys.
  * Provide links to EOS EVM and EOS Native landing sections.
- Kudos to design and org.

**Comment by Mikael337** [comment]
Hello @lparisc , the changes you requested have been applied to the dashboard's Documentation widget. Please review it whenever you get the chance. If you have any other changes, please let me know.

**Comment by ABurton22** [comment]
Submitted for payment processing.

Amy Burton

**Comment by Mikael337** [comment]
Hello @ABurton22, when can we expect the payment to be processed for the milestone?

**Comment by ABurton22** [comment]
Hi Mikael,

This was sent on 7/24/2023. Here are the payment details: https://bloks.io/transaction/4d40a761a462c3bf09540771f557054782da74602d0bebe6eed76816e5894e56

**Comment by Mikael337** [comment]
Hello @ABurton22, in the transaction the address used is "ctopjucyhyvhhbxbm55ygtqckitg9 qdp" where there is a space between '9' and 'qdp' at the end. The address we provided does not have a space : ctopjucyhyvhhbxbm55ygtqckitg9qdp

I believe this is why we did not receive the payment on our end, unless there is something else I am missing.

Please see image as well for reference:
image

**Comment by Mikael337** [comment]
Just received the payment.
Thank you!

**Pull request merged**
