### PR TITLE
EOS VISION X REDDIT

### PR DESCRIPTION
**Pull request by Creamyvanill**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/44

### CODE REVIEW

**Comment by Creamyvanill** [comment]
The milestone was based on the original milestone, leaving the corresponding links, I await comments, thank you all, happy night!

**Review by DenisCarriere — APPROVED** [review]
Reviewed the submitted documentation and can declare this milestone delivery completed.

**Comment by Creamyvanill** [comment]
Thank you very much Mr. Denis, now I'm waiting for the response from @nsjames  , thank you!

**Review by nsjames — APPROVED** [review]
Looks good to me 👍

**Comment by Creamyvanill** [comment]
Thanks guys, if you have any recommendations or anything else my DMs are open to your ideas and more.

I look forward to news by @tedcahalleos

**Pull request merged**
