### PR TITLE
chronicle milestone 3 delivery

### PR DESCRIPTION
**Pull request by cc32d9**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/XXX < please fill this in with the PR number of your application.

### CODE REVIEW

**Review by DenisCarriere — APPROVED** [review]
Nothing technical to review, deliverable is to provide maintenance & support for 18 months

👍 LGTM

**Review by linh2931 — APPROVED** [review]

**Comment by ericpassmore** [comment]
As Denis stated, did not find anything technical to review.

**Comment by BenjaminGormanPMP** [comment]
@cc32d9 can you please update with an invoice at https://docs.google.com/forms/d/e/1FAIpQLScxOkuWso5dJsQjCeOftGYNQrA2cdlkrKNB7B0piaTcBRwV9A/viewform.

**Comment by cc32d9** [comment]
Daniel is in a travel, he will create the invoice soon.

**Pull request merged**
