### PR TITLE
Milestone 1 — Account Login & View Collections

### PR DESCRIPTION
**Pull request by robrigo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/36 < please fill this in with the PR number of your application.

_Note: A pull request has been submitted to update the project location to https://github.com/FACINGS/collection-manager_

### CODE REVIEW

**Review by larryk85 — CHANGES_REQUESTED** [review]
I get "sh: next: not found", I had to install Next.js before running `yarn dev`.

For the `docker-compose` command, I copied it directly from the README and it fails with 'no such service'.

Also, the README is pretty sparse.  If you could please add a bit more meat to this that would be ultimately helpful.

I.e. Getting Started is just one command.  Having a good explanation to what the repo is and what is going to do is needed.  Having more detail around what I am getting started and what are the expectations would also be helpful.

**Comment by roadscape** [comment]
@larryk85, thank you for the feedback. We've fixed the docker command and added a bit of context and additional dev notes in the guide. The [repo](https://github.com/FACINGS/collection-manager) has been updated, and here is the specific commit: https://github.com/FACINGS/collection-manager/commit/3ded61a51597508a17fe523202c60497ebb0d388

**Comment by larryk85** [comment]
> @larryk85, thank you for the feedback. We've fixed the docker command and added a bit of context and additional dev notes in the guide. The [repo](https://github.com/FACINGS/collection-manager) has been updated, and here is the specific commit: [FACINGS/collection-manager@3ded61a](https://github.com/FACINGS/collection-manager/commit/3ded61a51597508a17fe523202c60497ebb0d388)

Great, I can now get the docker based server up and running but it has a runtime error "ReferenceError: regeneratorRuntime is not defined", not sure why though as it appears that it is properly referenced in the yarn.lock as a dependency.

**Comment by roadscape** [comment]
@larryk85 I'm having trouble reproducing the bug, are you able to provide any additional information, like a screenshot or a trace perhaps?

**Comment by roadscape** [comment]
Still unable to reproduce; we've tried the following OS/browser combinations using Docker method without issue:

Windows 11 - Chrome, Edge, Firefox, Brave
OSX - Safari, Chrome, Firefox
Debian - Firefox, Safari

**Comment by larryk85** [comment]
> Still unable to reproduce; we've tried the following OS/browser combinations using Docker method without issue:
> 
> Windows 11 - Chrome, Edge, Firefox, Brave OSX - Safari, Chrome, Firefox Debian - Firefox, Safari

If you've ran it on all of those, then I'm going suspect issues on my aide

**Review by larryk85 — APPROVED** [review]

**Comment by robrigo** [comment]
@larryk85 it looks like you aren't the only one seeing it. ) I set up my dev environment today on macOS and reproduced.

@ponglio is working on a fix for this now.

Screen Shot 2022-09-19 at 1 42 52 PM

**Comment by larryk85** [comment]
> @larryk85 it looks like you aren't the only one seeing it. ) I set up my dev environment today on macOS and reproduced.
> 
> @ponglio is working on a fix for this now.
> 
> Screen Shot 2022-09-19 at 1 42 52 PM

Ah fantastic, at least I'm not crazy.  Thanks for continuing to try it out.

**Comment by nsjames** [comment]
Docker works fine here, as does regular

Milestone deliverables look good 👍

**Review by nsjames — APPROVED** [review]

**Review by wanderingbort — APPROVED** [review]
Will the next deliverable be deployed to Jungle4? or will we be locally testing for the time being?

**Review by DenisCarriere — APPROVED** [review]
Works great! Able to build/deploy without any problems

**Comment by DenisCarriere** [comment]
Some minor comments when exploring the UI

1. Anchor app ID only accepts EOSIO name type
telegram-cloud-photo-size-1-5003585201774898052-y

2. Templates could have `img` blank, currently when undefined, throws an error:

> Test with: http://localhost:3001/collections/pomelo

```
upstream image response failed for https://ipfs.ledgerwise.io/ipfs/undefined 400
```

3. It would be highly recommended to make this library using **Typescript** instead of vanilla Javascript, at the moment the complexity is relatively low. Still, as more features are added, the code base will be unmanageable without a type-enforced language like Typescript. 

Overall this current milestone looks to be completed 👍

**Pull request merged**
