### PR TITLE
Neutroswap milestone 0 delivery

### PR DESCRIPTION
**Pull request by jonassunandar**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/222 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by nsjames** [comment]
The [second link](https://github.com/Nava-Labs/neutroswap-v2/blob/main/README.md) in the docs is broken

Everything else looks fine here, except the different between the stated milestone for the twitter threads:
- Originally it said "Publish twitter threads"
- But this milestone only has a typefully draft

What is the timeline for the release of those tweets?

**Review by wanderingbort — CHANGES_REQUESTED** [review]
I have the same concerns as @nsjames 

I believe the second link is broken because that repo is currently private (we see a 404 for the link and the repo itself).  

If that is the case, please add the reviewers to a role where they can at least view that repo and add in the document the timeline for opensourcing that repo

**Comment by jonassunandar** [comment]
Sorry about the broken link. Now there's no broken link and we have posted the V2 post. Please kindly check again @nsjames @wanderingbort

**Review by wanderingbort — APPROVED** [review]

**Review by nsjames — APPROVED** [review]

**Review by DenisCarriere — APPROVED** [review]
LGTM

**Comment by jonassunandar** [comment]
Hi @tedcahalleos, is there anything else I need to add for milestone 0? Neutroswap V2 smart contracts are ready, and we'd like to create new PR for the next milestone

**Pull request merged**
