### PR TITLE
chronicle milestone 1 delivery

### PR DESCRIPTION
**Pull request by cc32d9**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/26

### CODE REVIEW

**Comment by cc32d9** [comment]
it's running in production on a few dozen servers already. There's a new branch "chronos", a base for Chronicle 3.0, but it's not fully tested yet (it goes with https://github.com/EOSChronicleProject/chronos )

**Review by larryk85 — APPROVED** [review]

**Comment by cc32d9** [comment]
in the meantime, Chronicle 3.0 has been released, although it was not in scope of this grant.

**Review by ericpassmore — APPROVED** [review]
Reviewed and approved Release v2.7 Used the following steps

- Pinned build off v2.7 tag (no debug)
- Created config and ran `mode = scan-noexport` to validate working
- Created consumer service in Node/JS 
   - restarted with `mode = scan`
   - send a 1 SYS transfer via cleos and saw it printed out 

**Resources** 
- https://www.npmjs.com/package/chronicle-consumer
- https://github.com/EOSChronicleProject/chronicle-tutorial/tree/master

**Comment by tedcahalleos** [comment]
Payment has been submitted for processing.
Ted Cahall

**Pull request merged**
