### PR TITLE
Neutroswap Milestone 1&2

### PR DESCRIPTION
**Pull request by jonassunandar**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-milestones/pull/136 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by nsjames** [comment]
Hello! 
I'm going through the materials and I found a few issues. 

- License file link is not working, and I don't see a license in the repository
- The following contracts don't have their code verified: 
  - `0x5f4b3D92bcb944a0e9B231C42D0615F8A27Bbcc0` (NitroPoolFactory)
  - `0x72076068Bd08f5D0AE541075f1E317b3B1d46d8f` (FairAuctionFactory)
  - The [analytics page](https://testnet-analytics.neutroswap.io/) link is broken

(I see some issue with the explorer not be able to load the `0x96A064DB6CA1D45e59756D3DAc7CD249D4D742030` address right now and have elevated internally)

Something seems to be broken with subgraph development links
image

------

Contract foundry tests are all passing 👍
image

**Comment by jonassunandar** [comment]
Hi @nsjames thanks for pointing some issues

- Analytics link is changed to https://analytics.neutroswap.io/. We change the analytics directly to mainnet to test the accuracy of The Graph and for clearer data
- Currently V2 contracts are being audited now by SolidProof. No changes from the submitted contracts. Hopefully within this week we will update and verified all the contracts
- License and The Graph issues, I'll bring it to the team

**Comment by nsjames** [comment]
Thanks, looking forward to closing this one out 🙏

**Comment by jonassunandar** [comment]
> * License file link is not working, and I don't see a license in the repository
> Something seems to be broken with subgraph development links image

Hi James

1. The graph issues: you need to query some variables to test it. For example to get available all pairs [here](https://testnet.dbi.foundation/subgraphs/name/neutro-amm/graphql?query=query+MyQuery+%7B%0A++pairs+%7B%0A++++id%0A++%7D%0A%7D)
image

2. We have added the licenses here: [Neutroswap app](https://github.com/neutroswap/neutroswap-app/blob/dev/LICENSE.md) and [V2 contracts](https://github.com/neutroswap/neutroswap-v2-contracts/blob/main/LICENSE.md)


Please let me know if you found other issues

**Comment by nsjames** [comment]
Thanks, just waiting for those contracts to be verified and we're good to go.

**Comment by jonassunandar** [comment]
Hi @nsjames 
All the mainnet contracts are verified and audited by [SolidProof](https://github.com/solidproof/projects/blob/main/2024/NeutroSwapV2/SmartContract_Audit_Solidproof_NeutroSwapV2.pdf). Please take a look at [here](
https://github.com/neutroswap/neutroswap-v2-contracts/?tab=readme-ov-file#mainnet-contracts)

**Comment by nsjames** [comment]
Looking good, thanks!

**Review by nsjames — APPROVED** [review]

**Comment by tedcahalleos** [comment]
Approved.

**Pull request merged**
