### PR TITLE
EOS VISION AND REDDIT 2 

### PR DESCRIPTION
**Pull request by Creamyvanill**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/XXX < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by Creamyvanill** [comment]
Hello guys!, attentive to any comment, everything ready here. @ABurton22 @tedcahalleos

**Comment by Creamyvanill** [comment]
Good morning guys, attentive to any comments, thank you! @DenisCarriere @nsjames

**Review by DenisCarriere — APPROVED** [review]
Can confirm deliverables have been met for the current milestone.

**Comment by Creamyvanill** [comment]
Hey guys! Happy Monday, any news that I can clarify?

**Comment by nsjames** [comment]
Hey Veronica! @Creamyvanill 

The grants team here internally has reviewed your request for payment and did not approve it due to the estimated seven-month duration and lack of milestone proof of completion.

Per the EOS VISION AND REDDIT 2 #131 Grant Framework (https://github.com/eosnetworkfoundation/grant-framework/pull/131) :
- The estimated milestone duration is seven months from the start date.
- A monthly report (0B Metrics and Reports) to be submitted to ENF to display proof of milestone delivery. This report should document:
  - Increased upvote and karma to daily posts for Reddit EOS:
    -  May 2022 baseline (current upvote/karma state of daily posts for Reddit EOS prior to start of this initiative).
    - Seven-month target to achieve.
  - Statistics and analysis on growth of Reddit and Facebook:
    -  May 2022 baseline (current statistics for Reddit EOS prior to start of this initiative).
    - Seven-month target to achieve.
  - Attention and moderation of networks:
    - May 2022 baseline (current state prior to start of initiative).
    - Seven-month target to achieve.
  - Attention and translation in languages:
    - Seven-month target to achieve.
  - Growth of official ENF account on Reddit and Post on Facebook:
    - May 2022 baseline (status for Reddit and Facebook prior to start of this initiative). This baseline allows ENF to measure milestone achievements.
    - Seven-month target to achieve.

Also, can you please confirm a target date for the delivery of each monthly report?

**Comment by Creamyvanill** [comment]
I have updated the documentation with the milestones with the first analysis based on what you have asked me, I will insert it here as well.

Thank you!, I hope to promote Reddit, Facebook does not contain metrics or analysis because I only moderate it, I am not an administrator, but I will continue working on it. @nsjames  

https://docs.google.com/document/d/1CgJppRL8UBDaCgQyEDy72GgndY0TE3_vi1sWTjtDCyU/edit?usp=sharing

**Comment by Creamyvanill** [comment]
Important note: The reports will be published publicly through Our Blog at Bywire News:
https://bywire.news/u/eos_vision

Every 29 of Every Month:
We have set our goals and hope to achieve the objectives.

**Comment by nsjames** [comment]
Grants are paid out at the time of delivery of each milestone. Because of the way that this grant is structured, it means that it can only be paid out after the completion of the entire proposal (7 months from the start date) so that evaluators can ensure all deliverables were delivered.

**Comment by Creamyvanill** [comment]
This means that I have to... send the milestones again, right? @nsjames

**Comment by Creamyvanill** [comment]
Or that it will be paid in 7 months...?

**Pull request closed without merging**
