### PR TITLE
EVMNS_Audit_Milestone_1

### PR DESCRIPTION
**Pull request by chenminmin4**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/220 < please fill this in with the PR number of your application.

### CODE REVIEW

**Review by nsjames — APPROVED** [review]

**Review by wanderingbort — CHANGES_REQUESTED** [review]
This is great. 

The issues are marked as resolved in the audit but for history tracking purposes, do you mind linking the relevant PRs in the document (notes section of the audit row)

**Review by DenisCarriere — APPROVED** [review]
Audit is provided

https://github.com/evmns/EVMNS-Audit-Assistance/blob/main/EVMNS%20Audit%20Report-2023-10-9.pdf

**Comment by hdavis1988** [comment]
> This is great.
> 
> The issues are marked as resolved in the audit but for history tracking purposes, do you mind linking the relevant PRs in the document (notes section of the audit row)

Our communication with the auditing team is not conducted through Git, so there are no relevant PRs that can be linked to the document. 🤣

We apologize for any inconvenience caused and appreciate your understanding.

**Comment by nsjames** [comment]
@hdavis1988 I think @wanderingbort is referring to the commits on the public repo that show that the critical issues found in the audit were patched

**Comment by hdavis1988** [comment]
> @hdavis1988 I think @wanderingbort is referring to the commits on the public repo that show that the critical issues found in the audit were patched

Got it, thank you very much!

**Comment by hdavis1988** [comment]
> > This is great.
> > The issues are marked as resolved in the audit but for history tracking purposes, do you mind linking the relevant PRs in the document (notes section of the audit row)
> 
> Our communication with the auditing team is not conducted through Git, so there are no relevant PRs that can be linked to the document. 🤣
> 
> We apologize for any inconvenience caused and appreciate your understanding.

@wanderingbort 

Two historical commits on the public repo have been newly linked[ in this document](https://github.com/eosnetworkfoundation/grant-milestones/pull/137/commits/501a51e575634d999ff1323bfa39f228460b2f3e?short_path=538bb23#diff-538bb2396bdcada08ca1ff5f7979baf7defb974f37020780f88c5ecddb341328), both of them contain fixes for the issues identified during the audit process. Please feel free to let us know if there are any questions. 😄

Thank you very much!

**Review by wanderingbort — APPROVED** [review]

**Pull request merged**
