### PR TITLE
FACINGS NFT Collection Manager Stage 2 - Milestone 3 delivery

### PR DESCRIPTION
**Pull request by robrigo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/113

### CODE REVIEW

**Review by ericpassmore — APPROVED** [review]

**Review by linh2931 — APPROVED** [review]

**Review by DenisCarriere — CHANGES_REQUESTED** [review]
Most likely an easy fix, but when visiting the airdrop page, the page is broken:

https://creator.facings.io/eos/plugins/airdrop

image

or

image

However, if params are added `?type=default` it works

https://creator.facings.io/eos/plugins/airdrop?type=default

image

**Comment by DenisCarriere** [comment]
Not sure if this is the intended outcome, but when providing higher `Holding Quantity`, the list of "Accounts to airdrop" is replicated as if the account was only holding 1 asset.

## Assumed Scenario

If user holds 50 NFT's and min requirement is 50x NFT's, the "Accounts to airdrop" should be 1 account, not 50 times the same account.

image

**Comment by DenisCarriere** [comment]
When doing an airdrop, there's no "success page" which shows if the transaction was successful.

## Issue
- The page is refreshed and all previous data is removed

## Expecting
-  Confirmation modal with Transaction ID which can be used to verify if airdrop was successful (currently unknown status)

**Comment by roadscape** [comment]
@DenisCarriere thank you for this feedback! We have addressed the concerns and pushed updates to the code base at https://github.com/facings/collection-manager and the live instance at https://creator.facings.io/.

### 1. airdrop page routing bug

> Most likely an easy fix, but when visiting the airdrop page, the page is broken:
> https://creator.facings.io/eos/plugins/airdrop
> 
> However, if params are added `?type=default` it works
> https://creator.facings.io/eos/plugins/airdrop?type=default

**This issue is now resolved, default is truly default**

### 2. quantity/unique filters UX

> Not sure if this is the intended outcome, but when providing higher `Holding Quantity`, the list of "Accounts to airdrop" is replicated as if the account was only holding 1 asset.
> 
> **Assumed Scenario**
> If user holds 50 NFT's and min requirement is 50x NFT's, the "Accounts to airdrop" should be 1 account, not 50 times the same account.

We followed up with Steph and he said he didn't see a need for the multiples functionality. 
**We've modified the labels for clarity and added more detail in docs about the intended functionality:**
 - "Holding quantity" -> "Minimum entry quantity": allows you to specify the minimum number of NFTs required for an account to participate in the Airdrop.
- Rename "Unique accounts" to "Limit 1 per account" - false by default; if true, duplicate entries will be ignored.

### 3. airdrop - success status

> When doing an airdrop, there's no "success page" which shows if the transaction was successful.
> 
> **Issue**
> * The page is refreshed and all previous data is removed
> 
> **Expecting**
> * Confirmation modal with Transaction ID which can be used to verify if airdrop was successful (currently unknown status)

**We have added a "Success" dialog which both shows the transaction ID and links to its page on a public block explorer.**

image

**Review by DenisCarriere — APPROVED** [review]
Reviewed latest updates and everything looks good on my side 👍 

All above posted issues are resolved

**Review by wanderingbort — APPROVED** [review]

**Comment by ABurton22** [comment]
Milestone 3 submitted for payment.

**Pull request merged**
