### PR TITLE
EVMNS_Milestone_4&5

### PR DESCRIPTION
**Pull request by chenminmin4**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/106 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by chenminmin4** [comment]
EVMNS_milestone_4&5

**Comment by nsjames** [comment]
Hey @chenminmin4 

Please verify the smart contracts on the testnet so that I can validate them

I'm also getting some testing errors, looks like I might be missing something running on localhost:
```
 864 passing (2m)
  2 failing

  1) Contract: OffchainDNSResolver
       should respond to resolution requests with a CCIP read request to the DNS gateway:
     AssertionError: Expected transaction to be reverted with OffchainLookup("0x4bf010f1b9beDA5450a8dD702ED602A104ff65EE", ["https://localhost:8000/query"], "0x31b137b900000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000b0474657374047465737400000000000000000000000000000000000000000000", "0xb4a85801", "0x00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000b047465737404746573740000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000243b3b57de28f4f6752878f66fd9e3626dc2a299ee01cfe269be16e267e71046f1022271cb00000000000000000000000000000000000000000000000000000000"), but other exception was thrown: Error: VM Exception while processing transaction: reverted with an unrecognized custom error


  2) Contract: OffchainDNSResolver
       rejects calls to resolveCallback() with an invalid TXT record:
     AssertionError: Expected transaction to be reverted with CouldNotResolve, but other exception was thrown: Error: VM Exception while processing transaction: reverted with an unrecognized custom error
```

**Comment by nsjames** [comment]
Everything else looks fine, I also bought a name on the site and changes its details successfully.

**Comment by hdavis1988** [comment]
> Hey @chenminmin4
> 
> Please verify the smart contracts on the testnet so that I can validate them
> 
> I'm also getting some testing errors, looks like I might be missing something running on localhost:
> 
> ```
>  864 passing (2m)
>   2 failing
> 
>   1) Contract: OffchainDNSResolver
>        should respond to resolution requests with a CCIP read request to the DNS gateway:
>      AssertionError: Expected transaction to be reverted with OffchainLookup("0x4bf010f1b9beDA5450a8dD702ED602A104ff65EE", ["https://localhost:8000/query"], "0x31b137b900000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000b0474657374047465737400000000000000000000000000000000000000000000", "0xb4a85801", "0x00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000b047465737404746573740000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000243b3b57de28f4f6752878f66fd9e3626dc2a299ee01cfe269be16e267e71046f1022271cb00000000000000000000000000000000000000000000000000000000"), but other exception was thrown: Error: VM Exception while processing transaction: reverted with an unrecognized custom error
> 
> 
>   2) Contract: OffchainDNSResolver
>        rejects calls to resolveCallback() with an invalid TXT record:
>      AssertionError: Expected transaction to be reverted with CouldNotResolve, but other exception was thrown: Error: VM Exception while processing transaction: reverted with an unrecognized custom error
> ```

Hello, you can try the following steps:

1. Use git to update the project code to the latest version.
2. Rename the .env.org file in the root directory to .env, and fill in the corresponding account's private key and address according to the situation. Make sure they have enough EOS to complete the deployment. They can be the same account.
3. Our Node.js version is 16.20.2, please try to keep your version consistent with ours.
4. Use "yarn install" to install the dependencies.
5. Run "yarn hardhat deploy --network evm" to deploy the project to the EVM testnet. 

We hope this helps! If it still doesn't work, please let us know. 😊

**Comment by nsjames** [comment]
Still getting some errors: https://gist.github.com/nsjames/c6eabe815ad9416fe2617c75faf81571
image

**Comment by hdavis1988** [comment]
> Also I see the contracts are still not verified:
> 
> https://explorer.testnet.evm.eosnetwork.com/address/0x98bC6Ea0a95798F0307D833ACda6ed5817355f0A/contracts#address-tabs https://explorer.testnet.evm.eosnetwork.com/address/0x5A5aa55671638a46C527556D2fEbC747DD0DE57C/contracts#address-tabs https://explorer.testnet.evm.eosnetwork.com/address/0xed57d604E039b37e9F87E3C33683EbCF0d17A3A0/contracts#address-tabs https://explorer.testnet.evm.eosnetwork.com/address/0x300BB063d4e493B52ba9992C7c998D0618001427/contracts#address-tabs

So sorry! 🤣

According to the error you submitted, we have resubmitted the test script. 

Now you can pull the update again and rerun the test. 

Thank you for your patience!

**Comment by nsjames** [comment]
@hdavis1988 great, tests are passing now 🙏
image


I still don't see the contracts verified on the testnet though

**Comment by hdavis1988** [comment]
> I still don't see the contracts verified on the testnet though

Hello, the smart contract has been verified on the testnet. 

EVMRegistrarController
https://explorer.testnet.evm.eosnetwork.com/address/0x038573D60dB2a5c48b540bEd2145cF9BC2c2533D/contracts#address-tabs 

NameWrapper
https://explorer.testnet.evm.eosnetwork.com/address/0x40Af72b68f571000FAE70c9946d62da56B878Df8/contracts#address-tabs

( The smart contract on the mainnet has also been verified too. )

We didn't notice before that you had requested to verify the smart contract. This is our negligence. 😂

**Comment by hdavis1988** [comment]
> @hdavis1988 no problem, however the contracts that are specified in [this document at the bottom](https://github.com/eosnetworkfoundation/grant-milestones/blob/d04447e62f16e0d91075ebbfc453c7b39430ce50/deliveries/EVMNS_milestone_4%265.MD) are the ones I'm talking about.
> 
> I see that two of them are the same contract, but different addresses, if those are newly deployed you can just change them on the doc here. The other two also need to be verified though, please.

The contracts at [the bottom of the document](https://github.com/eosnetworkfoundation/grant-milestones/pull/121/commits/b53e85e99e6ed7eb4997f6cbe6e2a623d3676263) have all been updated to the latest version and have also been successfully verified. I believe there should be no errors in this regard. 😁

**Comment by nsjames** [comment]
Thanks! lgtm 👍

**Review by nsjames — APPROVED** [review]

**Review by wanderingbort — APPROVED** [review]

**Review by DenisCarriere — APPROVED** [review]
Looks good 👍  tests are functional

https://github.com/evmns/evmns-contracts#How-to-run-tests

```
$ npm t
```

**Review by arhag — APPROVED** [review]

**Pull request merged**
