### PR TITLE
FACINGS NFT Collection Manager Stage 2 - Milestone 2 delivery

### PR DESCRIPTION
**Pull request by robrigo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/113.

### CODE REVIEW

**Review by wanderingbort — APPROVED** [review]

**Review by linh2931 — COMMENTED** [review]
The documents look good. One minor thing is there are two "Accuracy" bullet items in the Benefits paragraph. You might consider combining them.

When I tried Public Test Instance https://collectionmanager.test.facings.io/ referred by the Test Guide, I got "This site can't be reached" error.

The "Getting Start" page https://github.com/FACINGS/collection-manager/blob/main/README.txt did not exist either.

**Comment by roadscape** [comment]
@linh2931 thank you for the report! We've fixed the outdated links in the testing guide, and reworded the "Accuracy" bullet point in the import plugin docs to highlight data integrity.

**Review by ericpassmore — APPROVED** [review]
LGTM

**Review by linh2931 — APPROVED** [review]
I logged into the public dev instance https://creator.facings.io/ using WAX Testnet wallet and played around all functionalities. All worked.

**Pull request merged**
