### PR TITLE
nice1-tools-ecosystem-milestone_3

### PR DESCRIPTION
**Pull request by alberuiza**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/eosnetworkfoundation/grant-milestones/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form](https://forms.gle/wLuAzXKa9qYrZQob9) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the EOS account name provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/eosnetworkfoundation/grant-framework/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/eosnetworkfoundation/grant-framework/pull/43 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by Nice1Blockchain** [comment]
@tedcahalleos , any news?

**Comment by nsjames** [comment]
I seem to be stuck here trying to log in

image

**Review by wanderingbort — APPROVED** [review]

**Comment by alberuiza** [comment]
> I seem to be stuck here trying to log in
> 
> image

I have tried to reproduce the problem but I have not been able to. Could you give me more information? Are you clicking on "Launch Anchor", via the QR? If you use Anchor Desktop, what version do you have installed? Does Anchor Desktop open when you click "Launch Anchor"? Are you using the n1holdernft1 account? Thanks in advance

**Comment by nsjames** [comment]
Works today, I think it was conflicts between anchor and wombat wallet.

**Review by nsjames — APPROVED** [review]

**Pull request merged**
